import { describe, it, expect, beforeEach, vi } from 'vitest'
import { mount, enableAutoUnmount } from '@vue/test-utils'
import { afterEach } from 'vitest'
import App from '../App.vue'
import { EXPANSIONS, OBJECTIVES, CARS } from '../data'
import { drawObjectives } from '../randomizer'

describe('randomizer', () => {
  const base = OBJECTIVES.filter((o) => o.source === 'base')
  const exp = OBJECTIVES.filter((o) => o.source === 'desert')
  it.each([0, 1, 2, 3])('honors ratio %i', (n) => {
    for (let i = 0; i < 30; i++) {
      const r = drawObjectives(base, exp, n)
      expect(r).toHaveLength(3)
      expect(r.filter((o) => o.source === 'desert')).toHaveLength(n)
    }
  })
  it('fills from other pool when one is short', () => {
    expect(drawObjectives(base, [], 2)).toHaveLength(3)
  })
})

describe('data', () => {
  it('is sorted alphabetically', () => {
    const names = EXPANSIONS.map((e) => e.name)
    expect(names).toEqual([...names].sort())
    expect(CARS.map((c) => c.name)).toEqual([...CARS.map((c) => c.name)].sort())
  })
})

describe('App wizard', () => {
  enableAutoUnmount(afterEach)
  beforeEach(() => {
    const data = new Map<string, string>()
    history.replaceState(null, '', '#/')
    vi.stubGlobal('scrollTo', vi.fn())
    vi.stubGlobal('localStorage', {
      getItem: (k: string) => data.get(k) ?? null,
      setItem: (k: string, v: string) => void data.set(k, v),
    })
  })
  const next = (w: ReturnType<typeof mount>) => w.find('button.big').trigger('click')
  it('goes expansions -> objectives -> pawns -> result with World', async () => {
    const w = mount(App)
    await next(w)
    expect(w.text()).toContain('Objective ratio')
    await next(w)
    expect(w.text()).toContain('Special pawns')
    await next(w)
    expect(w.text()).toContain('Additional setup:')
    expect(w.text()).toContain('traveler')
  })
  it('skips pawns without World', async () => {
    const w = mount(App)
    await w.findAll('button.plain')[EXPANSIONS.length]!.trigger('click')
    await next(w)
    await next(w)
    expect(w.text()).toContain('Additional setup:')
    expect(w.text()).not.toContain('Special pawns')
  })
  it('persists deselections', async () => {
    const w = mount(App)
    await w.findAll('button.plain')[0]!.trigger('click')
    await w.findAll('button.plain')[EXPANSIONS.length]!.trigger('click')
    await new Promise((r) => setTimeout(r))
    const saved = JSON.parse(localStorage.getItem('railroad-tiles-randomizer:v1')!)
    expect(saved.disabledExpansions).toEqual([EXPANSIONS[0]!.id])
    expect(saved.world).toBe(false)
  })
  it('excludes drawn items from the result screen', async () => {
    const w = mount(App)
    await next(w)
    await next(w)
    await next(w)
    const link = w.findAll('button.pill').find((b) => b.text().includes("Replace / exclude"))!
    await link.trigger('click')
    expect(w.text()).toContain('0 selected')
    await w.findAll('button.back').find((b) => b.text() === 'Cancel')!.trigger('click')
    await w.findAll('button.pill').find((b) => b.text().includes("Replace / exclude"))!.trigger('click')
    await w.findAll('button.link').find((b) => b.text() === 'all')!.trigger('click')
    await w.findAll('button.back').find((b) => b.text().startsWith('Just exclude'))!.trigger('click')
    await new Promise((r) => setTimeout(r))
    const saved = JSON.parse(localStorage.getItem('railroad-tiles-randomizer:v1')!)
    expect(saved.disabledObjectives).toHaveLength(3)
    expect(saved.disabledPawns).toHaveLength(3)
  })
  it('can also exclude the expansion', async () => {
    const w = mount(App)
    await next(w)
    await next(w)
    await next(w)
    await w.findAll('button.pill').find((b) => b.text().includes("Replace / exclude"))!.trigger('click')
    await w.findAll('button.link').find((b) => b.text() === 'all')!.trigger('click')
    expect(w.text()).toContain('6 selected')
    await w.find('.exp-col button.plain').trigger('click')
    expect(w.text()).toContain('7 selected')
    expect(w.find('button.big.small').attributes('disabled')).toBeDefined()
    await w.findAll('button.back').find((b) => b.text().startsWith('Just exclude'))!.trigger('click')
    await new Promise((r) => setTimeout(r))
    const saved = JSON.parse(localStorage.getItem('railroad-tiles-randomizer:v1')!)
    expect(saved.disabledExpansions).toHaveLength(1)
  })
  it('replaces selected tiles and excludes them', async () => {
    const w = mount(App)
    await next(w)
    await next(w)
    await next(w)
    const before = w.findAll('.result-items button.plain').map((b) => b.text())
    await w.findAll('button.pill').find((b) => b.text().includes('Replace / exclude'))!.trigger('click')
    await w.findAll('button.link').find((b) => b.text() === 'all')!.trigger('click')
    await w.find('button.big.small').trigger('click')
    await new Promise((r) => setTimeout(r))
    const saved = JSON.parse(localStorage.getItem('railroad-tiles-randomizer:v1')!)
    expect(saved.disabledObjectives).toHaveLength(3)
    expect(saved.disabledPawns).toHaveLength(3)
    const after = w.findAll('.result-items button.plain').map((b) => b.text())
    expect(after).toHaveLength(before.length)
    expect(after.filter((t) => before.includes(t))).toHaveLength(0)
    expect(w.text()).toContain('6 tile(s) replaced')
  })
  it('resets all settings', async () => {
    vi.stubGlobal('confirm', () => true)
    const w = mount(App)
    await w.findAll('button.plain')[0]!.trigger('click')
    await w.findAll('button.plain')[EXPANSIONS.length]!.trigger('click')
    await w.findAll('button.link').find((b) => b.text() === 'Reset all settings')!.trigger('click')
    await new Promise((r) => setTimeout(r))
    const saved = JSON.parse(localStorage.getItem('railroad-tiles-randomizer:v1')!)
    expect(saved.disabledExpansions).toEqual([])
    expect(saved.world).toBe(true)
  })
  it('shows setup rules for the chosen expansion', async () => {
    const w = mount(App)
    await next(w)
    await next(w)
    await next(w)
    expect(w.text()).toContain('Additional setup:')
    expect(w.find('.setup strong').exists()).toBe(true)
  })
  it('quick play jumps to the result', async () => {
    const w = mount(App)
    await w.find('button.quick').trigger('click')
    expect(w.text()).toContain('Additional setup:')
    expect(w.text()).toContain('Additional setup:')
  })
  it('restores the view from the URL', async () => {
    const w = mount(App)
    await w.find('button.quick').trigger('click')
    await new Promise((r) => setTimeout(r))
    const hash = location.hash
    expect(hash).toMatch(/^#\/result\//)
    const names = w.findAll('.obj-list .label').map((l) => l.text())
    w.unmount()
    const again = mount(App)
    await new Promise((r) => setTimeout(r))
    expect(again.text()).toContain('Additional setup:')
    expect(again.findAll('.obj-list .label').map((l) => l.text())).toEqual(names)
    expect(location.hash).toBe(hash)
  })
  it('scrolls to top on navigation', async () => {
    const w = mount(App)
    await next(w)
    await new Promise((r) => setTimeout(r))
    expect(window.scrollTo).toHaveBeenCalledWith(0, 0)
    expect(location.hash).toMatch(/^#\/objectives\//)
  })
  it('flips the two-player token', async () => {
    vi.useFakeTimers()
    const w = mount(App)
    await w.findAll('button.pill').find((b) => b.text().includes('token'))!.trigger('click')
    await w.find('.stage').trigger('click')
    expect(w.text()).toContain('Flipping')
    vi.advanceTimersByTime(1500)
    await w.vm.$nextTick()
    expect(w.text()).toMatch(/Remove the (left|right) column/)
    window.dispatchEvent(new KeyboardEvent('keydown', { key: ' ' }))
    await w.vm.$nextTick()
    expect(w.text()).toContain('Flipping')
    vi.useRealTimers()
  })
  it('shows rules from the info icon', async () => {
    const w = mount(App)
    await next(w)
    const icon = w.findAll('.cell').find((c) => c.text().includes('City Hall'))!.find('button.info')
    expect(icon.exists()).toBe(true)
    await icon.trigger('click')
    expect(w.find('[role=dialog]').text()).toContain('City Hall')
    expect(w.find('[role=dialog]').text()).toContain('four orthogonal directions')
  })
  it('defaults to the back and remembers the choice', async () => {
    const w = mount(App)
    await next(w)
    expect(w.find('.side-toggle button.on').text()).toBe('Back')
    await w.findAll('.side-toggle button').find((b) => b.text() === 'Front')!.trigger('click')
    await new Promise((r) => setTimeout(r))
    expect(JSON.parse(localStorage.getItem('railroad-tiles-randomizer:v1')!).objectiveSide).toBe('front')
    await next(w)
    await next(w)
    expect(w.find('.result-toggle button.on').text()).toBe('Front')
  })
})
